title: 지금, 여기
logo: /assets/img/logo.jpg
email: aquinasogames@gmail.com
description: 
site:
  favicon: https://raw.githubusercontent.com/aquinaso/aquinaso.github.io/main/favicon.ico
color-scheme: auto


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/aquinaso
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/youngchan-lee-37a804269/

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
